### ISSUE TITLE
Outline how two pen scenario is handled

### ISSUE THREAD

**Issue by mabian-ms** [WICG/ink-enhancement#17]
What happens in the case of two pens being used, on one or multiple presentation areas?

We've agreed to "last write wins" being the way to handle it, since we expect this to be a pretty niche case, but it isn't in the explainer anywhere.

**Comment by NavidZ** [comment]
Isn't the API going to be per pointer? So shouldn't we technically have one trail for each pointer separate from each other?
Although I'm not sure how this is supported within Windows APIs but we can achieve this at least on platforms that OS doesn't support the API and we wanted to just deliver this on Chromium only.

**Comment by mabian-ms** [comment]
Supporting more than one trail isn't currently planned for the Windows APIs as far as I know, but it does seem like it would be relatively straightforward to support 2+ within Chromium. Theoretically, we could even have one trail using Windows APIs and the rest using Chromium, to try to reduce the overall latency among all the trails as much as possible.

I think it does seem reasonable to support any number of trails, just falling back to the Chromium polyfill version for any beyond what the OS APIs support.
