### ISSUE TITLE
It is unclear how requestPresenter should behave if presentationArea argument isn't in any document or is in a different document to which the 'Ink' instance is bound to

### ISSUE THREAD

**Issue by smaug----** [WICG/ink-enhancement#22]
The title should be clear enough :)

**Comment by mabian-ms** [comment]
For the initial version of the spec, an error should be thrown if the Ink instance, presentationArea, and PointerEvent are not all associated with the same document. This is something we may change in a future version of the spec, but for keeping the initial version simple, I think it makes sense to throw an error in that case.

**Comment by smaug----** [comment]
Ok, so the current spec doesn't define this at all, so it needs to be updated. Throwing sounds reasonable.

**Comment by bmathwig** [comment]
Spec was updated. Closing.
