### ISSUE TITLE
It is unclear if requestPresenter should return (inside a promise) the same instance of InkPresenter if same parameters are passed in

### ISSUE THREAD

**Issue by smaug----** [WICG/ink-enhancement#23]
let presenter1 = await  navigator.ink.requestPresenter("", document.body);
let presenter2 = await  navigator.ink.requestPresenter("", document.body);
alert(presenter1 == presenter2);

Should that alert say true or false?

**Comment by mabian-ms** [comment]
That's a good question. I don't think there is any particular reason that we can't just make a new one every time, so we'll clarify in the spec that it should always return a new one.

**Comment by bmathwig** [comment]
Spec was updated. Closing.
