### ISSUE TITLE
Unclear how long ink trails last or if we need a way to stop them.

### ISSUE THREAD

**Issue by flackr** [WICG/ink-enhancement#28]
The [updateInkTrailStartPoint states](https://wicg.github.io/ink-enhancement/#dom-inkpresenter-updateinktrailstartpoint):

> This method indicates to the presenter which PointerEvent was used as the last rendering point for the current frame. This must be a trusted event that is in the same document as the InkPresenter.

Is it significant that this is the last rendering point for the current frame? I.e. does this call only render ink trails until the next animation frame or as long as that pointer exists? I suspect it must be the former, but the expected behavior from the presenter should be explained.

If it is forever, I suspect we need an API or to have a stroke style to stop rendering delegated ink trails for the pointer.

**Comment by mabian-ms** [comment]
A delegated ink trail should only be displayed for a single frame and then removed. Good call out, I'll clarify this in the spec in the next update.
