### ISSUE TITLE
Example code using coalesced events coordinates vs dispatch event coordinates

### ISSUE THREAD

**Issue by NavidZ** [WICG/ink-enhancement#3]
In the example code particularly this function:
```
renderInkPoint(evt) {
        let events = evt.getCoalescedEvents();
        events.push(evt);
        events.forEach(event => {
            this.renderStrokeSegment(event.x, event.y);
        });

        if (this.presenter) {
            this.presenterStyle = { color: "rgba(0, 0, 255, 0.5)", radius: 4 * evt.pressure };
            this.presenter.setLastRenderedPoint(evt, this.presenterStyle);
        }
    }
```

It seems the app is drawing based on the coalesced events and pass the dispatch event to the API. Obviously the dispatched event (i.e. `evt`) does have the coalesced events inside it. But the question is what point is considered the last drawn point by the app from the requestPresenter point of view. Is it going to be evt.clientX/Y or is it going to be coordinates of last element in evt.getCoalescedEvents(). 
These two coordinates are not necessarily the same and the current example assume that the API is indeed using the coordinates of the last event in evt.getCoalescedEvents(). However, if that is the case then an app who wants to use the dispatched events coordinates only cannot fully use the API.

I suggest to explicitly mention in the API that it will consider the passed event coordinates as the last drawn point and change this example in readme to instead pass the last coalesced event (which was drawn as part of this example) to the API.

**Comment by dlibby-** [comment]
In the example, evt actually is the last event in the `events` array due to `events.push(evt);`

But I will clarify this in both the prose and the code example since it is not clear enough. Thanks!

**Comment by dlibby-** [comment]
Let me know if the updated wording/comments are clearer. Thanks!
