### ISSUE TITLE
Come up with a better function name than setLastRenderedPoint

### ISSUE THREAD

**Issue by dlibby-** [WICG/ink-enhancement#7]
The side-effect of a UA/OS rendered ink trail should be more explicit in the name

**Comment by mabian-ms** [comment]
Function names are certainly not my specialty, but spent a little bit of time trying to come up with a better one for this. How does something like `DelegatedInkTrailStartingPoint` sound?

We've already been calling the feature Delegated Ink Trail, so it matches that better, and calling it delegated in the name makes it a little more clear that drawing the trail will be delegated to the OS or UA. It also makes it more clear that you are providing the point where the ink trail should begin - the last point that was rendered by the application.

Thoughts
